// File generated by Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCADdOvp2Mi5Qvx8mBx1dGPiiAM1H8gEZ0',
    appId: '1:469405287112:web:b5b158259a984a6e6edbfd',
    messagingSenderId: '469405287112',
    projectId: 'finease-27a62',
    authDomain: 'finease-27a62.firebaseapp.com',
    storageBucket: 'finease-27a62.firebasestorage.app',
    measurementId: 'G-M4VSSSEY80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACyhJV14oEAFAUs7caEnBWzO6VqS_kknM',
    appId: '1:469405287112:android:46263ac3d93253fc6edbfd',
    messagingSenderId: '469405287112',
    projectId: 'finease-27a62',
    storageBucket: 'finease-27a62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvknOKkcNC73Dw3sa3hVMNKbhAGYNZvKM',
    appId: '1:469405287112:ios:ce09ec7103c244f56edbfd',
    messagingSenderId: '469405287112',
    projectId: 'finease-27a62',
    storageBucket: 'finease-27a62.firebasestorage.app',
    iosBundleId: 'com.example.finease',
  );
}
